docclass/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("myapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.contrib.auth import views as auth
from django.urls import path, include
from myapp import accounts as user_view
from myapp.views import index,threatscan,email,url

app_name="myapp"
urlpatterns = [
    path('',index,name="home"),
    path('accounts/login/', user_view.Login, name ='login'),
    path('logout/', auth.LogoutView.as_view(template_name ='index.html'), name ='logout'),
    path('accounts/register/', user_view.register, name ='register'),
    path('threatscan/',threatscan,name='threatscan'),
    path('email_scan/',email,name='email'),
    path('url_scan/',url,name='url'),

    # path("classification/",filupload,name="fileupload")
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http import HttpRequest
from django.contrib.auth import get_user_model

User=get_user_model()

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
 
 
 
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length = 20)
    first_name = forms.CharField(max_length = 20)
    last_name = forms.CharField(max_length = 20)
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_no', 'password1', 'password2']

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
import warnings
warnings.filterwarnings('ignore')
import tensorflow_hub as hub
import json
import pprint
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from myapp.urlana import pri_domain,abnormal_url,httpSecure,digit_count,special_count,letter_count,URL_Shortening,having_ip
capabilities = DesiredCapabilities.CHROME
import pdb

# capabilities["loggingPrefs"] = {"performance": "ALL"}  # chromedriver < ~75
capabilities["goog:loggingPrefs"] = {"performance": "ALL"}  # chromedriver 75+

driver = webdriver.Chrome(
    r"/Users/lalitbohara/Desktop/chromedriver",
    desired_capabilities=capabilities,
)


def process_browser_logs_for_network_events(logs):
    """
    Return only logs which have a method that start with "Network.response", "Network.request", or "Network.webSocket"
    since we're interested in the network events specifically.
    """
    for entry in logs:
        log = json.loads(entry["message"])["message"]
       
        if (
                "Network.response" in log["method"]
                or "Network.request" in log["method"]
                or "Network.webSocket" in log["method"]
        ):
            yield log
import pickle
with open("url_model.pkl", "rb") as file:
    logreg = pickle.load(file)
# embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
# def preprocess_email(email_text):
#     email_embedding = embed([email_text])
#     return email_embedding

# import tensorflow.keras as keras
# loaded_model = keras.models.load_model("universal_sentence_encoder_model.h5")
# @login_required
def index(request):
    
    context={}
    if request.method=='POST' and request.POST.get('choice')=='1' or request.POST.get('choice')=='2' or request.POST.get('choice')=='3':
        ch=request.POST.get('choice')

        print("first choice")
        print(ch)
       
    if request.method=='POST' and request.POST.get('choice1')=='FREE' or request.POST.get('choice1')=='LEVEL1' or request.POST.get('choice1')=='LEVEL2':
    # if request.method=='POST' and request.POST.get('choice1')=='FREE':
        ch=request.POST.get('choice1')
        print("second choice")
        print(ch)
        return redirect("myapp:fileupload")
    return render(request,"index.html")
def threatscan(request):
    if request.method=='POST':
        ch=request.POST.get("threat")
        if ch=='1':
            return redirect("myapp:email")
        if ch=='2':
            return redirect("myapp:url")
     
        if ch==3:
            pass
        print(ch)
    return render(request,"type.html")
def email(request):
    if request.method=='POST':
        ch=request.POST.get("input")
        print(ch)
    return render(request,"analysis/emailresult.html")

def url(request):
    dt=[]
    results = []
    context={}
    chart1 = None
    chart2 = None
    chart3 = None
    chart4=None
    if request.method=='POST':
        ch=request.POST.get("input")
        driver.get(ch)
        
        logs = driver.get_log("performance")
        events = process_browser_logs_for_network_events(logs)
        with open("log_entries.txt", "wt") as out:
            for event in events:
                pprint.pprint(event, stream=out)
        file_path = 'log_entries.txt'
        # Let's open and read the contents
        with open(file_path, 'r') as file:
            contents = file.readlines()
        # Extract URLs assuming they follow the pattern 'url': '<URL>'
        import re

        # Regex pattern to find URLs in the given pattern
        pattern = r"'url':\s*'(https?://[^\s']*)'"

        # Finding all URLs using regex
        urls = re.findall(pattern, ''.join(contents))
        pattern = r"'url':\s*'(https?://[^\s']*)'"

        # Use a set to store unique URLs
        unique_urls = set(re.findall(pattern, ''.join(contents)))

        # Print or process the unique URLs
        features = ['@', '?', '-', '=', '.', '#', '%', '+', '$', '!', '*', ',', '//']
        for url in unique_urls:
            dt.append(url)

        for url in dt:
            # Preprocess the URL and extract features
            url_features = [url.count(a) for a in features]
            # url_features.append(pri_domain(url))
            url_features.append(abnormal_url(url))
            url_features.append(httpSecure(url))
            url_features.append(digit_count(url))
            url_features.append(special_count(url))
            url_features.append(letter_count(url))
            url_features.append(URL_Shortening(url))
            url_features.append(having_ip(url))

            # Make predictions using the trained model
            prediction = logreg.predict([url_features])[0]

            # Append URL and prediction to the results list
            results.append({"URL": url, "Result": "Spam" if prediction == 0 else "Ham"})

        # Convert results list to JSON format
        # results=results[:5]
        # json_results = json.dumps(results, indent=4)
        import pandas as pd
        df = pd.DataFrame(results)
        df['special_count'] = df['URL'].apply(special_count)
        df['digit_count'] = df['URL'].apply(digit_count)
        df['abnormal_url'] = df['URL'].apply(abnormal_url)
        df['having_ip'] = df['URL'].apply(having_ip)
        df['char count'] = df['URL'].apply(letter_count)
        from myapp.urlsplot import hamspambar,charcount,scatter,charcounths
        chart1 = hamspambar(df).to_html()
        chart2 = charcount(df).to_html()
        chart3 = scatter(df).to_html()
        chart4 = charcounths(df).to_html()

    return render(request,"analysis/urlresult.html",{"results": results,"chart1":chart1,"chart2":chart2,"chart3":chart3,"chart4":chart4})

templates/analysis/emailresult.html
<!DOCTYPE html>
<html>
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

body, html {
  height: 100%;
  line-height: 1.8;
}

.centered-form {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh; /* Adjust as needed */
}

.chat-input {
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 10px;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}

.chat-input input[type="text"],
.chat-input input[type="file"],
.chat-input input[type="submit"] {
  width: 100%;
  margin-bottom: 10px;
  padding: 10px;
  border: none;
  border-radius: 5px;
  box-sizing: border-box;
}

.chat-input input[type="submit"] {
  background-color: #4CAF50;
  color: white;
  cursor: pointer;
}

.chat-input input[type="submit"]:hover {
  background-color: #45a049;
}


</style>
</head>
<body>

<!-- Navbar (sit on top) -->
    <a href="{% url 'myapp:home' %}" class="w3-bar-item w3-button w3-wide"><i class="fa fa-unlock"></i> ThreatScan</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="#team" class="w3-bar-item w3-button"><i class="fa fa-user"></i> TEAM</a>
      <a href="#work" class="w3-bar-item w3-button"><i class="fa fa-th"></i> WORK</a>
      {% if user.is_authenticated %}
      <a href="" class="w3-bar-item w3-button"><i class="fa fa-th"></i> DASHBOARD</a>
      <a onclick="logoutFunction()" class="w3-bar-item w3-button"><i class="fa fa-user"></i> LOGOUT</a>
	  <script>
		function logoutFunction() {
		  // Create a form element
		  var form = document.createElement('form');
		  form.method = 'POST';
		  form.action = "{% url 'myapp:logout' %}";
	  
		  // Add a CSRF token input field
		  var csrfToken = document.createElement('input');
		  csrfToken.type = 'hidden';
		  csrfToken.name = 'csrfmiddlewaretoken';
		  csrfToken.value = "{{ csrf_token }}";
		  form.appendChild(csrfToken);
	  
		  // Append the form to the document body and submit it
		  document.body.appendChild(form);
		  form.submit();
		}
	  </script>
      <a href="" class="w3-bar-item w3-button"><i class="fa fa-user"></i> Welcome @{{user}}</a>
      {% else %}
      <a href="{% url 'myapp:login' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> LOGIN</a>
      <a href="{% url 'myapp:register' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> REGESTER</a>
      {% endif %}
    </div>
  
<div class="centered-form">
    <form class="chat-input" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" placeholder="Type a message" name="input" id="input">
        <input type="file" name="file" id="file" accept="image/*">
        <input type="submit" value="Submit">
    </form>
</div>

    
</body>

</html>

templates/analysis/urlresult.html
<!DOCTYPE html>
<html>
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

body, html {
  height: 100%;
  line-height: 1.8;
}

.centered-form {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh; /* Adjust as needed */
}

.chat-input {
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 10px;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  margin-bottom: 0; /* Updated to remove margin-bottom */
}

.chat-input input[type="text"],
.chat-input input[type="file"],
.chat-input input[type="submit"] {
  width: 100%;
  margin-bottom: 0px;
  padding: 10px;
  border: none;
  border-radius: 5px;
  box-sizing: border-box;
}

.chat-input input[type="submit"] {
  background-color: #4CAF50;
  color: white;
  cursor: pointer;
}

.chat-input input[type="submit"]:hover {
  background-color: #45a049;
}
table {
    width: 100%;
    border-collapse: collapse;
}
th, td {
    border: 1px solid black;
    padding: 8px;
    word-wrap: break-word;
    max-width: 200px; /* Adjust max-width as needed */
    overflow: hidden;
    text-overflow: ellipsis;
}
</style>
</head>
<body>

<!-- Navbar (sit on top) -->
    <a href="{% url 'myapp:home' %}" class="w3-bar-item w3-button w3-wide"><i class="fa fa-unlock"></i> ThreatScan</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="#team" class="w3-bar-item w3-button"><i class="fa fa-user"></i> TEAM</a>
      <a href="#work" class="w3-bar-item w3-button"><i class="fa fa-th"></i> WORK</a>
      {% if user.is_authenticated %}
      <a href="" class="w3-bar-item w3-button"><i class="fa fa-th"></i> DASHBOARD</a>
      <a onclick="logoutFunction()" class="w3-bar-item w3-button"><i class="fa fa-user"></i> LOGOUT</a>
      <script>
        function logoutFunction() {
          // Create a form element
          var form = document.createElement('form');
          form.method = 'POST';
          form.action = "{% url 'myapp:logout' %}";
      
          // Add a CSRF token input field
          var csrfToken = document.createElement('input');
          csrfToken.type = 'hidden';
          csrfToken.name = 'csrfmiddlewaretoken';
          csrfToken.value = "{{ csrf_token }}";
          form.appendChild(csrfToken);
      
          // Append the form to the document body and submit it
          document.body.appendChild(form);
          form.submit();
        }
      </script>
      <a href="" class="w3-bar-item w3-button"><i class="fa fa-user"></i> Welcome @{{user}}</a>
      {% else %}
      <a href="{% url 'myapp:login' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> LOGIN</a>
      <a href="{% url 'myapp:register' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> REGESTER</a>
      {% endif %}
    </div>
  
<div class="centered-form">
    <form class="chat-input" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Type a message" name="input" id="input">
        {% comment %} <input type="file" name="file" id="file" accept="image/*"> {% endcomment %}
        <input type="submit" value="Submit">
    </form>
</div>
{% if request.method == 'POST' %}
<h1>URL Result Analysis</h1>
<table border="1">
    <thead>
        <tr>
            <th style="width: 50%;">URL</th>
            <th style="width: 50%;">Result</th>
        </tr>
    </thead>
    <tbody>
        {% for result in results %}
        <tr>
            <td>{{ result.URL }}</td>
            <td>{{ result.Result }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% load static %}
<link rel="stylesheet" href="{% static 'charts.css' %}">
<header>
	<h1>VISUALIZATIONS</h1>
	<p></p>
</header>

<div class="-fx-image-gal">
    <div class="-fx-gal-item">
        <div class="-fx-gal-image-thumb" tabindex="1">
            <a href="" target="_blank">
                {{ chart1|safe }}
            </a>
        </div>
    </div>

    <div class="-fx-gal-item">
        <div class="-fx-gal-image-thumb" tabindex="1">
            <a href="" target="_blank">
                {{ chart2|safe }}
            </a>
        </div>
    </div>

    <div class="-fx-gal-item">
        <div class="-fx-gal-image-thumb" tabindex="1">
            <a href="" target="_blank">
                {{ chart3|safe }}
            </a>
        </div>
    </div>

    <div class="-fx-gal-item">
        <div class="-fx-gal-image-thumb" tabindex="1">
            <a href="" target="_blank">
                {{ chart4|safe }}
            </a>
        </div>
    </div>
</div>



{% endif %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

body, html {
  height: 100%;
  line-height: 1.8;
}

/* Full height image header */
.bgimg-1 {
  background-position: center;
  background-size: cover;
  background-image: url("/w3images/mac.jpg");
  min-height: 100%;
}

.w3-bar .w3-button {
  padding: 16px;
}


/*General Styles*/

* {
	margin: 0;
	padding: 0;
	box-sizing: border-box;
}

html {
	font-size: 16px;
	font-family: "Raleway", sans-serif;
	color: #555;
}

ul,
nav {
	list-style: none;
}

a {
	text-decoration: none;
	opacity: 0.75;
	color: #fff;
}

a:hover {
	opacity: 1;
}

a.btn {
	border-radius: 4px;
	text-transform: uppercase;
	font-weight: bold;
	text-align: center;
	background-color: #e07e7b;
	opacity: 1;
	transition: all 400ms;
}

a.btn:hover {
	background-color: #ce5856;
}

section {
	display: flex;
	flex-direction: column;
	align-items: center;
	padding: 100px 80px;
}

section:not(.hero):nth-child(even) {
	background-color: #f5f5f5;
}
li {
    color: red;
}

.grid {
	width: 100%;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
}

hr {
	width: 250px;
	height: 3px;
	background-color: #e07e7b;
	border: 0;
	margin-bottom: 50px;
}



section h3.title {
	text-transform: capitalize;
	font: bold 48px "Amatic SC", sans-serif;
	margin-bottom: 30px;
	text-align: center;
}

section p {
	max-width: 775px;
	line-height: 2;
	padding: 0 20px;
	margin-bottom: 30px;
	text-align: center;
}

@media (max-width: 800px) {
	section {
		padding: 50px 20px;
	}
}

/*Header Styles*/

header {
	position: absolute;
	width: 100%;
	display: flex;
	justify-content: space-between;
	align-items: center;
	padding: 35px 100px 0;
	animation: 1s fadein 0.5s forwards;
	opacity: 0;
	color: #fff;
	z-index: 2;
}

@keyframes fadein {
	100% {
		opacity: 1;
	}
}

header h2 {
	font-family: "Amatic SC", sans-serif;
}

header nav {
	display: flex;
	margin-right: -15px;
}

header nav li {
	margin: 0 15px;
}

@media (max-width: 800px) {
	header {
		padding: 20px 50px;
		flex-direction: column;
	}

	header h2 {
		margin-bottom: 15px;
	}
}

/*Hero Styles*/

.hero {
	position: relative;
	justify-content: center;
	text-align: center;
	min-height: 100vh;
	color: #fff;
}

.hero .background-image {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-image: url("https://african.business/wp-content/uploads/2023/02/adobestock_293068579.jpeg");
	background-size: cover;
	z-index: -1;
	background-color: #80a3db;
}

.hero h1 {
	font: 72px "Amatic SC", sans-serif;
	text-shadow: 2px 2px rgba(0, 0, 0, 0.3);
	margin-bottom: 15px;
}

.hero h3 {
	font: 28px "Raleway", sans-serif;
	font-weight: 300;
	text-shadow: 2px 2px rgba(0, 0, 0, 0.3);
	margin-bottom: 40px;
}

.hero a.btn {
	padding: 20px 46px;
}

.hero-content-area {
	opacity: 0;
	margin-top: 100px;
	animation: 1s slidefade 1s forwards;
}

@keyframes slidefade {
	100% {
		opacity: 1;
		margin: 0;
	}
}

@media (max-width: 800px) {
	.hero {
		min-height: 600px;
	}

	.hero h1 {
		font-size: 48px;
	}

	.hero h3 {
		font-size: 24px;
	}

	.hero a.btn {
		padding: 15px 40px;
	}
}
    .pdf-box {
            width: 400px;
            height: 600px;
            border: 1px solid #ccc;
            overflow: auto;
			display: inline-block;
			margin-right: 20px;
    }
</style>
</head>
<body>

<!-- Navbar (sit on top) -->
    <a href="{% url 'myapp:home' %}" class="w3-bar-item w3-button w3-wide"><i class="fa fa-unlock"></i> ThreatScan</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="#team" class="w3-bar-item w3-button"><i class="fa fa-user"></i> TEAM</a>
      <a href="#work" class="w3-bar-item w3-button"><i class="fa fa-th"></i> WORK</a>
      {% if user.is_authenticated %}
      <a href="" class="w3-bar-item w3-button"><i class="fa fa-th"></i> DASHBOARD</a>
      <a onclick="logoutFunction()" class="w3-bar-item w3-button"><i class="fa fa-user"></i> LOGOUT</a>
	  <script>
		function logoutFunction() {
		  // Create a form element
		  var form = document.createElement('form');
		  form.method = 'POST';
		  form.action = "{% url 'myapp:logout' %}";
	  
		  // Add a CSRF token input field
		  var csrfToken = document.createElement('input');
		  csrfToken.type = 'hidden';
		  csrfToken.name = 'csrfmiddlewaretoken';
		  csrfToken.value = "{{ csrf_token }}";
		  form.appendChild(csrfToken);
	  
		  // Append the form to the document body and submit it
		  document.body.appendChild(form);
		  form.submit();
		}
	  </script>
      <a href="" class="w3-bar-item w3-button"><i class="fa fa-user"></i> Welcome @{{user}}</a>
      {% else %}
      <a href="{% url 'myapp:login' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> LOGIN</a>
      <a href="{% url 'myapp:register' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> REGESTER</a>
      {% endif %}
    </div>

    <!-- Hide right-floated links on small screens and replace them with a menu icon -->
	{% block content %}
	{% endblock content %}

<!-- FORM -1 -->
{% if user.is_authenticated %}
<link href="https://fonts.googleapis.com/css?family=Amatic+SC|Raleway" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<section class="hero">
  <div class="background-image"></div>
  <div class="hero-content-area">
	<h1>Safeguarding cyber infrastructure through accurate threat classification!</h1>
	<h3>Promoting trust and compliance in cyber security</h3>
	<a href="{% url 'myapp:threatscan' %}" class="btn">Start Threat Scan</a>
  </div>
</section>
	  {% else %}

	  <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Raleway" rel="stylesheet">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	  <section class="hero">
		<div class="background-image"></div>
		<div class="hero-content-area">
			<h1>Safeguarding cyber infrastructure through accurate threat classification!</h1>
			<h3>Promoting trust and compliance in cyber security</h3>
		  <a href="{% url 'myapp:register' %}" class="btn">Regester Now</a>
		</div>
	  </section>
	  {% endif %}
  
</body>

</html>

templates/user/email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

templates/user/login.html
{% extends 'index.html' %}
{% block content %}
{% load crispy_forms_tags %}

<style>
  .custom_form form {
    background-color: rgba(205, 219, 187, 0.7);
    padding: 40px;
    border-radius: 15px;
    margin-bottom: 30px;
}

.custom_form form sub a {
  color: #fff;
}

.custom_form form fieldset {
  border: 0;
}

.custom_form form fieldset .form-group {
  text-align: left;
  margin-bottom: 15px;
}

.custom_form form fieldset .form-group label {
  display: block;
  margin-bottom: 5px;
}
.custom_form form fieldset .form-group input {
  display: block;
  width: 100%;
  height: 42px;
  border: 0;
  outline: none;
  padding: 10px 15px;
  border-radius: 8px;
  margin-bottom: 5px;
}
.custom_form form button {
  background-color: #e07e7b;
    color: #fff;
    text-align: center;
    padding: 10px 30px;
    font-size: 19px;
    cursor: pointer;
    border: 0;
    text-transform: capitalize;
    border-radius: 6px;
}
</style>
 <div class="custom_form content-section col-md-8 col-md-offset-2">
  <center>
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
   <center>
    <button class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in"></span> &nbsp; login</button>
  </center>
  <br/>
  <sub style="text-align: left;"><a href="{% url 'myapp:register' %}" >don't have account,sign up</a></sub>
  </form>
</center>
 </div>
 {% endblock content %}

templates/user/register.html
{% extends 'index.html' %}
{% block content %}
{% load crispy_forms_tags %}


<style>

.custom_form form {
    background-color: rgba(210, 230, 214, 0.7);
    padding: 40px;
    border-radius: 15px;
    margin-bottom: 30px;
}

.custom_form form sub a {
  color: #fff;
}

.custom_form form fieldset {
  border: 0;
}

.custom_form form fieldset .form-group {
  text-align: left;
  margin-bottom: 15px;
}

.custom_form form fieldset .form-group label {
  display: block;
  margin-bottom: 5px;
}
.custom_form form fieldset .form-group input {
  display: block;
  width: 100%;
  height: 42px;
  border: 0;
  outline: none;
  padding: 10px 15px;
  border-radius: 8px;
  margin-bottom: 5px;
}
.custom_form form button {
  background-color: #e07e7b;
    color: #fff;
    text-align: center;
    padding: 10px 30px;
    font-size: 19px;
    cursor: pointer;
    border: 0;
    text-transform: capitalize;
    border-radius: 6px;
}
</style>

<div class="custom_form content-section col-md-8 col-md-offset-2">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
    <center>
      <button type="submit"><span class="glyphicon glyphicon-check"></span>sign up</button>
    </center>
    <br />
    <sub><a href="{% url "myapp:login" %}">Already have an account ?</a></sub>
  </form>
</div>
{% endblock content %}